---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
   version: "4.10"
   storage_account_name: "sunbird-installation-test-{{ version }}"
   region: us-east-2
   vpc_name: "installation-test-{{ version }}"
   subnet_name: "installation-test-subnet-{{ version }}"
   security_group: sunbird-setup
   eks_role: ecrfullaccess
   aws_access_key: aws-22344
   aws_secret_key: 123456
   ssh_public_key_file_location: home/deployer/deployer.pub
   vm_names:
     - jenkins
     - kp
     - dp
     - yarn
     - db
     - others
   instance_type: t2.micro
   eks_version: 1.23
   private_containers:
     - private
     - artifacts
     - management
     - results
     - backups
     - label
   public_containers:
     - contents
     - public
  tasks:
    - name: Writing resource info to azure-resources.txt
        copy:
          dest: azure-resources.txt
          content: |-
            ================================================================
            jenkins_public_ip="{{ public_ip.state.ip_address }}"
            ecr_password="{{ registry.registries[0].credentials.password }}"
            ecr_registry_server="{{ registry.registries[0].login_server }}"
            ecr_username="{{ registry.registries[0].name }}"
            storage_account_name="{{ storage_account_name }}"
            storage_account_key="{{ storage_account_info.storageaccounts[0].primary_endpoints.key }}"
            storage_account_endpoint="{{ storage_account_info.storageaccounts[0].primary_endpoints.blob.endpoint }}"
            storage_account_sas_token="{{ sas_token.stdout }}"
            S3 bucket list= "{{ result['buckets'] }}"
      - name: Writing machine ips to azure-resources.txt
        lineinfile:
          state: present
          insertbefore: EOF
          dest: azure-resources.txt
          line: "{{ item.networkinterfaces[0].name }}={{ item.networkinterfaces[0].ip_configurations[0].private_ip_address }}"
        with_items: "{{ nics.results }}"
        loop_control:
          label: "{{  item.networkinterfaces[0].name  }}"
      - debug:
          msg: ansible variable values to update for the installation is stored in "sunbird-devops/deploy/azure-resources.txt"
      tags:
        - info
