---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
   version: "4.10"
   rg_name: "sunbird-installation-test-{{ version }}"
   region: us-east-2
   vpc_name: "installation-test-{{ version }}"
   subnet_name: "installation-test-subnet-{{ version }}"
   security_group: sunbird-setup
   eks_role: ecrfullaccess
   aws_access_key: aws-22344
   aws_secret_key: 123456
   ssh_public_key_file_location: home/deployer/deployer.pub
   vm_names:
     - jenkins
     - kp
     - dp
     - yarn
     - db
     - others
   instance_type: t2.micro
   eks_version: 1.23
   private_containers:
     - private
     - artifacts
     - management
     - results
     - backups
     - label
   public_containers:
     - contents
     - public
  tasks:
    - name: Create private bucket
      s3_bucket:
         name: "{{ item }}"
         permission: private
         region: "{{ region }}"
      with_items: "{{ private_containers }}"
    - name: Create public containers #bucket
      s3_bucket:
         container: "{{ item }}"
         acl: public-read
         region: "{{ region }}"
      with_items: "{{ public_containers }}"
