---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
   version: "4.10"
   rg_name: "sunbird-installation-test-{{ version }}"
   region: us-east-2
   vpc_name: "installation-test-{{ version }}"
   subnet_name: "installation-test-subnet-{{ version }}"
   security_group: sunbird-setup
   vm_names:
     - jenkins
     - kp
     - dp
     - yarn
     - db
     - others
   instance_type: t2.xlarge
    # To get correct verions, run
    # az aks get-versions -l centralindia -o table
   eks_version: 1.23
   private_containers:
     - private
     - artifacts
     - management
     - results
     - backups
     - label
   public_containers:
     - contents
     - public
  tasks:
   - name: creating ec2 group
     ec2_group:
        name: "{{ security_group }}"
        region: "{{ region }}"
        vpc: "{{vpc_name}}"
      rules:
       - proto: tcp
         ports:
         - 80
         cidr_ip: 0.0.0.0/0
      register: security group
