---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
   version: "4.10"
   rg_name: "sunbird-installation-test-{{ version }}"
   region: us-east-2
   vpc_name: "installation-test-{{ version }}"
   subnet_name: "installation-test-subnet-{{ version }}"
   security_group: sunbird-setup
   vm_names:
     - jenkins
     - kp
     - dp
     - yarn
     - db
     - others
   instance_type: t2.xlarge
    # To get correct verions, run
    # az aks get-versions -l centralindia -o table
   eks_version: 1.23
   private_containers:
     - private
     - artifacts
     - management
     - results
     - backups
     - label
   public_containers:
     - contents
     - public
  tasks:
    - name: Creating vm {{ name }}
      ec2_instance: #or ec2:
        resource_group: "{{ rg_name }}" 
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        user: deployer  ##
        ssh_password_enabled: false
        assign_public_ip: no ##
        volume_type: gp2 #(or) io1
        volume_size: 250
        network_interfaces: "{{ item }}"
        state: present
        allocated: "{{ allocate | d(true) }}"
        group: "{{ security_group }}"
        ssh_public_keys:
          - path: /home/deployer/.ssh/authorized_keys
            key_data: "{{ lookup('file', ssh_public_key_file_location) }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
      with_items: "{{ vm_names }}"
      tags:
        - vm
